name: Docker image

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest #or self-hosted runner if used

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker Image
        run: docker build -t <image-name> .
      - name: Tag the Docker Image
        run: docker tag <image-name> <tag-name>
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Push
        run: docker push <tag-name>
